name: test build
on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: install pnpm
        with:
          run_install: false

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"

      - name: test build
        run: pnpm install && pnpm build
